/**
 * AASRA Master Multi-Crop Advisory, Protection & Biological Management Matrix
 * Covers 40+ major Indian field, cash, pulse, vegetable, fruit, and plantation crops.
 * Grounded with certified CIBRC / ICAR / Syngenta label rates and agronomic best practices.
 */

export interface CropDiseasePestItem {
  name: string;
  nameHi: string;
  type: "insect_pest" | "fungal_disease" | "bacterial_disease" | "abiotic_stress" | "deficiency";
  symptomsEn: string;
  symptomsHi: string;
  solutionEn: string;
  solutionHi: string;
  recommendedProduct: string;
  category: string;
  activeIngredient: string;
  dosePerAcre: string;
  waterLitersPerAcre: number;
  timing: string;
}

export interface CropAgronomicProfile {
  cropId: string;
  nameEn: string;
  nameHi: string;
  category: "cereal" | "pulse" | "oilseed" | "cash_crop" | "vegetable" | "fruit" | "spice" | "plantation";
  season: "Kharif" | "Rabi" | "Zaid" | "Year-Round";
  standardVariety: string;
  optimalDayTemp: number;
  heatStressLimitDay: number;
  optimalNightTemp: number;
  nightHeatStressLimit: number;
  frostTemp: number;
  baseGdd: number;
  waterReqMm: [number, number];
  criticalStages: string[];
  fertilizerNpkKgPerAcre: [number, number, number];
  diseasesAndPests: CropDiseasePestItem[];
  stressBusterRecommendation: {
    product: string;
    dosePerAcre: string;
    waterLiters: number;
    timing: string;
    benefit: string;
  };
}

export const CROP_ADVISORY_MATRIX: Record<string, CropAgronomicProfile> = {
  // ─────────────────────────────────────────────────────────────
  // 1. CEREALS
  // ─────────────────────────────────────────────────────────────
  wheat: {
    cropId: "wheat",
    nameEn: "Wheat (गेहूँ)",
    nameHi: "गेहूँ",
    category: "cereal",
    season: "Rabi",
    standardVariety: "HD-2967 / Sharbati / Lokwan / GW-322",
    optimalDayTemp: 22,
    heatStressLimitDay: 32,
    optimalNightTemp: 14,
    nightHeatStressLimit: 22,
    frostTemp: 0,
    baseGdd: 4.5,
    waterReqMm: [400, 500],
    criticalStages: ["CRI (21 DAS)", "Tillering (40-45 DAS)", "Jointing / Booting (60-65 DAS)", "Flowering / Grain Fill (80-90 DAS)"],
    fertilizerNpkKgPerAcre: [50, 25, 15],
    stressBusterRecommendation: {
      product: "Syngenta Quantis®",
      dosePerAcre: "250–400 ml/acre",
      waterLiters: 150,
      timing: "At booting or terminal heat stress onset",
      benefit: "Protects against terminal heat stress and prevents shrivelled grain filling.",
    },
    diseasesAndPests: [
      {
        name: "Yellow / Stripe Rust (Puccinia striiformis)",
        nameHi: "पीला रतुआ / हल्दी रोग",
        type: "fungal_disease",
        symptomsEn: "Yellow powdery stripes running parallel along leaf veins, wiping off on fingers.",
        symptomsHi: "पत्तियों पर नसों के समानांतर पीले रंग की धारियां, उंगली से छूने पर पीला पाउडर लगना।",
        solutionEn: "Apply Propiconazole or Azoxystrobin immediately upon detecting first foci.",
        solutionHi: "पहला लक्षण दिखते ही फफूंदनाशक का तत्काल छिड़काव करें।",
        recommendedProduct: "Syngenta Tilt® (Propiconazole 25% EC) or Amistar Top®",
        category: "Fungicide",
        activeIngredient: "Propiconazole 25% EC / Azoxystrobin + Difenoconazole",
        dosePerAcre: "200 ml/acre",
        waterLitersPerAcre: 150,
        timing: "Early morning upon initial yellow stripe detection",
      },
      {
        name: "Wheat Aphid (Mahun / Chepa)",
        nameHi: "गेहूँ का माहू / चेपा",
        type: "insect_pest",
        symptomsEn: "Clusters of small green/black insects sucking sap from ears and leaves, causing sticky honeydew.",
        symptomsHi: "बालियों और पत्तियों पर छोटे हरे/काले कीड़ों का झुंड रस चूसना, बाली कमजोर होना।",
        solutionEn: "Spray Thiamethoxam when aphid population exceeds 10–15 aphids per earhead.",
        solutionHi: "प्रति बाली 10-15 माहू दिखने पर कीटनाशक का छिड़काव करें।",
        recommendedProduct: "Syngenta Actara® (Thiamethoxam 25% WG)",
        category: "Insecticide",
        activeIngredient: "Thiamethoxam 25% WG",
        dosePerAcre: "50–80 g/acre",
        waterLitersPerAcre: 150,
        timing: "Late afternoon or morning at milky stage",
      },
      {
        name: "Terminal Heat Stress (Respiration Loss)",
        nameHi: "पछता तापमान तनाव / लू का असर",
        type: "abiotic_stress",
        symptomsEn: "Forced maturity, premature drying of flag leaf, light shrivelled grains.",
        symptomsHi: "समय से पहले पत्तियां सूखना, बालियों में दाना हल्का व सिकुड़ा रह जाना।",
        solutionEn: "Spray biostimulant with light evening irrigation during grain filling.",
        solutionHi: "दाना भराव के समय हल्की शाम की सिंचाई व बायोस्टिमुलेंट का छिड़काव करें।",
        recommendedProduct: "Syngenta Quantis®",
        category: "Biostimulant",
        activeIngredient: "Amino Acids + Peptides + Osmoprotectants",
        dosePerAcre: "300–400 ml/acre",
        waterLitersPerAcre: 150,
        timing: "At heading/anthesis before maximum temperature spike",
      },
    ],
  },

  rice: {
    cropId: "rice",
    nameEn: "Rice / Paddy (धान)",
    nameHi: "धान",
    category: "cereal",
    season: "Kharif",
    standardVariety: "Pusa Basmati 1121 / PR-126 / Sona Masoori",
    optimalDayTemp: 30,
    heatStressLimitDay: 38,
    optimalNightTemp: 22,
    nightHeatStressLimit: 28,
    frostTemp: 8,
    baseGdd: 10,
    waterReqMm: [1000, 1400],
    criticalStages: ["Transplanting (15-20 DAS)", "Active Tillering (30-40 DAT)", "Panicle Initiation (60-70 DAT)", "Grain Filling"],
    fertilizerNpkKgPerAcre: [48, 24, 24],
    stressBusterRecommendation: {
      product: "Syngenta Isabion® + Quantis®",
      dosePerAcre: "400 ml/acre",
      waterLiters: 200,
      timing: "At active tillering and panicle emergence",
      benefit: "Enhances tillering, panicle length, and protects against high temperature spike during anthesis.",
    },
    diseasesAndPests: [
      {
        name: "Stem Borer & Leaf Folder (Tana Chhedak & Patta Lapetak)",
        nameHi: "तना छेदक एवं पत्ता लपेटक",
        type: "insect_pest",
        symptomsEn: "Dead hearts in vegetative stage, White heads in reproductive stage, folded leaves with scraped chlorophyll.",
        symptomsHi: "तने का सूखना (Dead Heart), बालियों का सफेद पड़ना (White Earhead) तथा पत्तों का मुड़ना।",
        solutionEn: "Apply granular insecticide in standing water or foliar spray at peak moth emergence.",
        solutionHi: "शुरुआती अवस्था में खेत में दवा का छिड़काव या दानेदार दवा डालें।",
        recommendedProduct: "Syngenta Virtako® (2.5 kg/acre soil) or Ampligo® (80-100 ml/acre spray)",
        category: "Insecticide",
        activeIngredient: "Chlorantraniliprole + Thiamethoxam / Lambda-cyhalothrin",
        dosePerAcre: "80–100 ml/acre (Spray) or 2.5 kg/acre (Granule)",
        waterLitersPerAcre: 200,
        timing: "Early morning upon seeing white moth flights or 1st dead heart",
      },
      {
        name: "Sheath Blight & Blast (Jhursa / Sheath Rog)",
        nameHi: "शीथ ब्लाइट एवं झुलसा रोग",
        type: "fungal_disease",
        symptomsEn: "Oval or spindle-shaped greenish-grey lesions with brown borders on leaf sheaths and diamond spots on leaves.",
        symptomsHi: "तने और पत्तों पर नाव के आकार के भूरे-धूसर धब्बे, पत्तियां ऊपर से सूखना।",
        solutionEn: "Spray broad-spectrum strobilurin fungicide targeting plant base and upper foliage.",
        solutionHi: "पौधे के निचले तने तक पहुंचे ऐसे फफूंदनाशक का छिड़काव करें।",
        recommendedProduct: "Syngenta Amistar Top®",
        category: "Fungicide",
        activeIngredient: "Azoxystrobin 18.2% + Difenoconazole 11.4% SC",
        dosePerAcre: "200 ml/acre",
        waterLitersPerAcre: 200,
        timing: "At maximum tillering to booting stage when humidity >85%",
      },
      {
        name: "Brown Plant Hopper - BPH (Bhoora Mahu)",
        nameHi: "भूरा माहू / तेला (BPH)",
        type: "insect_pest",
        symptomsEn: "Hopper burn: Circular patches of dried yellow-brown plants in center of field.",
        symptomsHi: "खेत के बीच में गोल घेरे में पौधे सूखना (हॉपर बर्न), तने के निचले हिस्से पर भूरे कीड़े।",
        solutionEn: "Spray systemically directed at the base of the plant stem, drain field water.",
        solutionHi: "दवा का छिड़काव सीधे तने के निचले भाग पर करें।",
        recommendedProduct: "Syngenta Chess® (Pymetrozine 50% WDG)",
        category: "Insecticide",
        activeIngredient: "Pymetrozine 50% WDG",
        dosePerAcre: "120 g/acre",
        waterLitersPerAcre: 200,
        timing: "Direct nozzle to plant base during early morning",
      },
    ],
  },

  maize: {
    cropId: "maize",
    nameEn: "Maize / Corn (मक्का)",
    nameHi: "मक्का",
    category: "cereal",
    season: "Kharif",
    standardVariety: "Pioneer 3396 / Bio-9681 / Dekalb 9108",
    optimalDayTemp: 28,
    heatStressLimitDay: 38,
    optimalNightTemp: 18,
    nightHeatStressLimit: 26,
    frostTemp: 2,
    baseGdd: 10,
    waterReqMm: [500, 750],
    criticalStages: ["Knee-high Stage (30-35 DAS)", "Tasseling (50-55 DAS)", "Silking & Cob Fill (65-75 DAS)"],
    fertilizerNpkKgPerAcre: [48, 24, 20],
    stressBusterRecommendation: {
      product: "Syngenta Quantis®",
      dosePerAcre: "300 ml/acre",
      waterLiters: 175,
      timing: "Tasseling to silking stage under high heat or moisture deficit",
      benefit: "Prevents tassel blasting and poor pollination due to dry heat.",
    },
    diseasesAndPests: [
      {
        name: "Fall Armyworm - FAW (Spodoptera frugiperda / Sainik Keet)",
        nameHi: "फॉल आर्मीवर्म (सैनिक सुंडी)",
        type: "insect_pest",
        symptomsEn: "Pinholes on leaves, ragged shot-hole feeding in whorl, heavy sawdust-like frass inside central funnel.",
        symptomsHi: "पत्तियों में छलनी जैसे छेद, गोभ (Whorl) के अंदर लकड़ी के बुरादे जैसा मल और इल्ली।",
        solutionEn: "Spray targeted directly into central whorl immediately on 5% plant damage.",
        solutionHi: "दवा का घोल सीधे मक्के की गोभ (मध्य भाग) के अंदर डालें।",
        recommendedProduct: "Syngenta Evicent™ or Ampligo®",
        category: "Insecticide",
        activeIngredient: "Emamectin benzoate 5% + Lufenuron 40% WG / Ampligo®",
        dosePerAcre: "60 ml/acre (Evicent) or 80-100 ml/acre (Ampligo)",
        waterLitersPerAcre: 150,
        timing: "Early morning, nozzle aimed directly down into whorl",
      },
      {
        name: "Maydis Leaf Blight / Turcicum Blight",
        nameHi: "मक्का का पत्ता झुलसा रोग",
        type: "fungal_disease",
        symptomsEn: "Long elliptical boat-shaped grey-green to tan lesions starting on lower leaves and moving up.",
        symptomsHi: "निचली पत्तियों पर लंबे भूरे-धूसर धब्बे जो बाद में पूरी पत्ती को सुखा देते हैं।",
        solutionEn: "Apply strobilurin fungicide before lesions spread to ear leaves.",
        solutionHi: "रोग के शुरुआती लक्षण दिखते ही फफूंदनाशक का छिड़काव करें।",
        recommendedProduct: "Syngenta Amistar Top®",
        category: "Fungicide",
        activeIngredient: "Azoxystrobin + Difenoconazole",
        dosePerAcre: "200 ml/acre",
        waterLitersPerAcre: 175,
        timing: "Foliar spray at knee-high to pre-tassel stage",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 2. OILSEEDS
  // ─────────────────────────────────────────────────────────────
  soybean: {
    cropId: "soybean",
    nameEn: "Soybean (सोयाबीन)",
    nameHi: "सोयाबीन",
    category: "oilseed",
    season: "Kharif",
    standardVariety: "JS-335 / JS-9560 / NRC-37 / Black Bold",
    optimalDayTemp: 30,
    heatStressLimitDay: 38,
    optimalNightTemp: 22,
    nightHeatStressLimit: 28,
    frostTemp: 2,
    baseGdd: 10,
    waterReqMm: [450, 650],
    criticalStages: ["Flower Initiation (30-35 DAS)", "Pod Setting (45-55 DAS)", "Grain Bulking (65-75 DAS)"],
    fertilizerNpkKgPerAcre: [12, 32, 16],
    stressBusterRecommendation: {
      product: "Syngenta Quantis®",
      dosePerAcre: "250–350 ml/acre",
      waterLiters: 150,
      timing: "Flower initiation / pod setting during rain break or night temp >25°C",
      benefit: "Reduces flower & pod drop caused by thermal stress or monsoon dry spells.",
    },
    diseasesAndPests: [
      {
        name: "Semilooper, Spodoptera & Girdle Beetle (Girdle Ring Keet)",
        nameHi: "सेमीलूपर, इल्ली एवं गर्डल बीटल (चक्रीय कीट)",
        type: "insect_pest",
        symptomsEn: "Leaves skeletonized, rings cut around petioles/stems causing drooping and drying of upper branches.",
        symptomsHi: "पत्तियों को छलनी करना, तने पर 2 गोल छल्ले बनाकर पौधे के ऊपरी भाग को सुखाना।",
        solutionEn: "Apply dual-action broad-spectrum insecticide covering egg hatch and caterpillar instar.",
        solutionHi: "इल्ली और गर्डल बीटल दोनों के नियंत्रण हेतु संयुक्त कीटनाशक का छिड़काव करें।",
        recommendedProduct: "Syngenta Ampligo®",
        category: "Insecticide",
        activeIngredient: "Chlorantraniliprole 10% + Lambda-cyhalothrin 5% ZC",
        dosePerAcre: "80–100 ml/acre",
        waterLitersPerAcre: 150,
        timing: "Early morning (6–9 AM) at early caterpillar instar appearance",
      },
      {
        name: "Yellow Mosaic Virus & Anthracnose / Pod Blight",
        nameHi: "पीला मोजेक वायरस एवं एन्थ्रेक्नोज (फली झुलसा)",
        type: "fungal_disease",
        symptomsEn: "Bright yellow mosaic patches on leaves (spread by Whitefly), black sunken spots on pods and stems.",
        symptomsHi: "पत्तियों का पीला पड़ना (सफेद मक्खी द्वारा फैलाव), फलियों पर काले धब्बे और दाना सिकुड़ना।",
        solutionEn: "Control whitefly vector with Thiamethoxam and spray Azoxystrobin for fungal pod blight.",
        solutionHi: "सफेद मक्खी को रोकने के लिए कीटनाशक तथा फली झुलसा के लिए फफूंदनाशक का छिड़काव करें।",
        recommendedProduct: "Syngenta Amistar Top® (Fungicide) + Alika® (Vector Control)",
        category: "Protection Combo",
        activeIngredient: "Amistar Top 200 ml + Alika 80 ml / acre",
        dosePerAcre: "200 ml Amistar Top + 80 ml Alika / acre",
        waterLitersPerAcre: 150,
        timing: "At first mosaic or pod lesion symptom",
      },
    ],
  },

  mustard: {
    cropId: "mustard",
    nameEn: "Mustard / Rapeseed (सरसों / राई)",
    nameHi: "सरसों",
    category: "oilseed",
    season: "Rabi",
    standardVariety: "Pusa Bold / Giriraj / RH-749 / Pioneer 45S46",
    optimalDayTemp: 24,
    heatStressLimitDay: 32,
    optimalNightTemp: 10,
    nightHeatStressLimit: 20,
    frostTemp: 0,
    baseGdd: 5,
    waterReqMm: [250, 400],
    criticalStages: ["Rosette / Vegetative (25-30 DAS)", "Flowering (45-55 DAS)", "Siliqua / Pod Fill (70-80 DAS)"],
    fertilizerNpkKgPerAcre: [32, 16, 12],
    stressBusterRecommendation: {
      product: "Syngenta Quantis® + Isabion®",
      dosePerAcre: "250 ml/acre",
      waterLiters: 150,
      timing: "Flowering stage if sudden temperature rise occurs",
      benefit: "Prevents siliqua blasting and improves oil content.",
    },
    diseasesAndPests: [
      {
        name: "Mustard Aphid (Chepa / Moyla)",
        nameHi: "सरसों का चेपा / मोयला / माहू",
        type: "insect_pest",
        symptomsEn: "Massive colonies of yellow-green aphids sucking sap from inflorescence, pods, and tender shoots; curling leaves.",
        symptomsHi: "फूलों और फलियों पर अनगिनत माहू कीड़ों का जमावड़ा, रस चूसना व तेल का प्रतिशत गिरना।",
        solutionEn: "Apply systemic neonicotinoid as soon as 10% twigs show aphid colonies.",
        solutionHi: "टहनियों पर माहू दिखते ही तुरंत सिस्टेमिक कीटनाशक का छिड़काव करें।",
        recommendedProduct: "Syngenta Actara®",
        category: "Insecticide",
        activeIngredient: "Thiamethoxam 25% WG",
        dosePerAcre: "50–80 g/acre",
        waterLitersPerAcre: 150,
        timing: "Early morning or late evening during calm winds",
      },
      {
        name: "Alternaria Blight & White Rust (Safed Roli)",
        nameHi: "अल्टरनेरिया झुलसा एवं सफेद रतुआ (रोली)",
        type: "fungal_disease",
        symptomsEn: "Concentric dark brown target spots on leaves, white raised blisters on underside of leaves and staghead deformities.",
        symptomsHi: "पत्तियों पर गोल छल्लेदार काले धब्बे, निचली सतह पर सफेद फफोले और फूलों का विकृत होना।",
        solutionEn: "Spray Ridomil Gold or Amistar Top upon seeing first white pustules or leaf spots.",
        solutionHi: "सफेद फफोले या काले धब्बे दिखते ही फफूंदनाशक का छिड़काव करें।",
        recommendedProduct: "Syngenta Ridomil Gold® or Amistar Top®",
        category: "Fungicide",
        activeIngredient: "Metalaxyl-M + Mancozeb / Azoxystrobin + Difenoconazole",
        dosePerAcre: "300 g/acre (Ridomil) or 200 ml/acre (Amistar Top)",
        waterLitersPerAcre: 150,
        timing: "At flowering/pod development stage",
      },
    ],
  },

  groundnut: {
    cropId: "groundnut",
    nameEn: "Groundnut / Peanut (मूंगफली)",
    nameHi: "मूंगफली",
    category: "oilseed",
    season: "Kharif",
    standardVariety: "GG-20 / TAG-24 / Kadiri-6 / TG-37A",
    optimalDayTemp: 30,
    heatStressLimitDay: 38,
    optimalNightTemp: 20,
    nightHeatStressLimit: 28,
    frostTemp: 4,
    baseGdd: 10,
    waterReqMm: [500, 700],
    criticalStages: ["Pegging Stage (35-45 DAS)", "Pod Formation (55-70 DAS)", "Pod Maturation (80-95 DAS)"],
    fertilizerNpkKgPerAcre: [10, 24, 18],
    stressBusterRecommendation: {
      product: "Syngenta Quantis®",
      dosePerAcre: "300 ml/acre",
      waterLiters: 150,
      timing: "At start of pegging into soil",
      benefit: "Facilitates smooth peg penetration and enhances uniform kernel weight.",
    },
    diseasesAndPests: [
      {
        name: "Tikka Leaf Spot & Rust (Tikka Rog)",
        nameHi: "टिक्का रोग एवं गेरुई (Rust)",
        type: "fungal_disease",
        symptomsEn: "Circular dark brown spots with yellow halos on upper leaf surface, causing severe defoliation.",
        symptomsHi: "पत्तियों पर पीले घेरे वाले गहरे भूरे-काले धब्बे, पत्तियां समय से पहले झड़ना।",
        solutionEn: "Spray triazole/strobilurin fungicide at 40 and 60 days after sowing.",
        solutionHi: "बुवाई के 40 व 60 दिन बाद फफूंदनाशक का छिड़काव करें।",
        recommendedProduct: "Syngenta Amistar Top® or Tilt®",
        category: "Fungicide",
        activeIngredient: "Azoxystrobin + Difenoconazole / Propiconazole 25% EC",
        dosePerAcre: "200 ml/acre",
        waterLitersPerAcre: 150,
        timing: "Early morning or late afternoon",
      },
      {
        name: "White Grub & Spodoptera (Gobar Keeda / Ledi)",
        nameHi: "सफेद लट (White Grub) एवं तम्बाकू इल्ली",
        type: "insect_pest",
        symptomsEn: "Roots sheared by subterranean white grubs leading to wilting patches; foliage eaten by Spodoptera.",
        symptomsHi: "जड़ों को सफेद लट द्वारा काटना जिससे पौधे सूखने लगते हैं; पत्तियों को इल्ली द्वारा खाना।",
        solutionEn: "Apply soil insecticide before monsoon or drench at root zone.",
        solutionHi: "खेत की तैयारी या बुवाई के समय दानेदार कीटनाशक डालें।",
        recommendedProduct: "Syngenta Virtako® (Soil) / Ampligo® (Foliar)",
        category: "Insecticide",
        activeIngredient: "Chlorantraniliprole + Thiamethoxam",
        dosePerAcre: "2.5 kg/acre (Soil) or 100 ml/acre (Spray)",
        waterLitersPerAcre: 150,
        timing: "At sowing / early vegetative stage",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 3. CASH & COMMERCIAL CROPS
  // ─────────────────────────────────────────────────────────────
  cotton: {
    cropId: "cotton",
    nameEn: "Cotton (कपास)",
    nameHi: "कपास",
    category: "cash_crop",
    season: "Kharif",
    standardVariety: "Bt Cotton II / RCH-659 / Shankar-6 / Bunny",
    optimalDayTemp: 32,
    heatStressLimitDay: 40,
    optimalNightTemp: 22,
    nightHeatStressLimit: 30,
    frostTemp: 5,
    baseGdd: 15,
    waterReqMm: [700, 1100],
    criticalStages: ["Squaring (40-50 DAS)", "Flowering (60-70 DAS)", "Boll Development (80-110 DAS)", "Boll Bursting"],
    fertilizerNpkKgPerAcre: [48, 24, 24],
    stressBusterRecommendation: {
      product: "Syngenta Quantis® + Isabion®",
      dosePerAcre: "350 ml/acre",
      waterLiters: 200,
      timing: "Squaring and peak flowering stages",
      benefit: "Significantly reduces square (guddi) and boll dropping caused by high day/night heat stress.",
    },
    diseasesAndPests: [
      {
        name: "Pink Bollworm (Gulabi Sundi - Pectinophora gossypiella)",
        nameHi: "गुलाबी सुंडी (Pink Bollworm)",
        type: "insect_pest",
        symptomsEn: "Rosetted flowers, bored holes plugged with excreta in developing green bolls, stained lint.",
        symptomsHi: "गुलाब जैसे मुड़े फूल (Rosetted Flower), बोंड (Boll) में छेद और अंदर रुई व बीज का सड़ना।",
        solutionEn: "Install pheromone traps and spray Ampligo at 8 moths/trap/night threshold.",
        solutionHi: "फेरोमोन ट्रैप लगाएं और आर्थिक क्षति स्तर पार होते ही अनुशंसित कीटनाशक का छिड़काव करें।",
        recommendedProduct: "Syngenta Ampligo®",
        category: "Insecticide",
        activeIngredient: "Chlorantraniliprole 10% + Lambda-cyhalothrin 5% ZC",
        dosePerAcre: "100 ml/acre",
        waterLitersPerAcre: 200,
        timing: "At 60–75 DAS during early evening (pest is nocturnal)",
      },
      {
        name: "Sucking Pest Complex (Whitefly, Thrips, Jassids, Aphids)",
        nameHi: "सफेद मक्खी, थ्रिप्स, हरा तेला (सकिंग पेस्ट)",
        type: "insect_pest",
        symptomsEn: "Upward leaf curling (Thrips), downward leaf cupping with yellow margins (Jassids), sooty mould (Whitefly).",
        symptomsHi: "पत्तियों का मुड़ना, किनारों से पीला पड़ना तथा पत्तियों पर काला फफूंद जमना।",
        solutionEn: "Spray specialized sucking pest insecticide with thorough lower leaf coverage.",
        solutionHi: "पत्तियों की निचली सतह को भिगोते हुए कीटनाशक का छिड़काव करें।",
        recommendedProduct: "Syngenta Pegasus® or Alika®",
        category: "Insecticide",
        activeIngredient: "Diafenthiuron 50% WP / Thiamethoxam + Lambda-cyhalothrin",
        dosePerAcre: "200–250 g/acre (Pegasus) or 80 ml/acre (Alika)",
        waterLitersPerAcre: 200,
        timing: "Early morning before high sun activity",
      },
      {
        name: "Alternaria Leaf Spot & Grey Mildew (Dahiya Rog)",
        nameHi: "अल्टरनेरिया पत्ता धब्बा एवं दहिया रोग (Grey Mildew)",
        type: "fungal_disease",
        symptomsEn: "Greyish-white powdery coating on leaf underside with yellow patches on top; brown concentric leaf spots.",
        symptomsHi: "पत्ती की निचली सतह पर सफेद-धूसर चूर्ण जैसी परत और ऊपरी सतह पर पीले चकत्ते।",
        solutionEn: "Spray broad-spectrum strobilurin fungicide at canopy closure.",
        solutionHi: "रोग का फैलाव रोकने हेतु फफूंदनाशक का छिड़काव करें।",
        recommendedProduct: "Syngenta Amistar Top®",
        category: "Fungicide",
        activeIngredient: "Azoxystrobin + Difenoconazole",
        dosePerAcre: "200 ml/acre",
        waterLitersPerAcre: 200,
        timing: "At canopy closure during humid spells",
      },
    ],
  },

  sugarcane: {
    cropId: "sugarcane",
    nameEn: "Sugarcane (गन्ना)",
    nameHi: "गन्ना",
    category: "cash_crop",
    season: "Year-Round",
    standardVariety: "Co-0238 / Co-86032 / Co-0118 / Co-15023",
    optimalDayTemp: 30,
    heatStressLimitDay: 40,
    optimalNightTemp: 20,
    nightHeatStressLimit: 28,
    frostTemp: 5,
    baseGdd: 12,
    waterReqMm: [1500, 2200],
    criticalStages: ["Germination (0-45 DAS)", "Tillering (45-120 DAS)", "Grand Growth (120-270 DAS)", "Maturity / Ripening"],
    fertilizerNpkKgPerAcre: [80, 32, 32],
    stressBusterRecommendation: {
      product: "Syngenta Isabion® + Quantis®",
      dosePerAcre: "500 ml/acre",
      waterLiters: 250,
      timing: "Grand growth and summer drought periods",
      benefit: "Enhances internodal elongation, cane girth, and maintains sucrose accumulation.",
    },
    diseasesAndPests: [
      {
        name: "Early Shoot Borer & Top Borer (Kansua / Choti Chhedak)",
        nameHi: "कंसुआ (Early Shoot Borer) एवं चोटी छेदक",
        type: "insect_pest",
        symptomsEn: "Dead hearts in young shoots emitting foul smell when pulled; shot-holes across leaf blades and bunchy top.",
        symptomsHi: "शुरुआती कल्लों में डेड हार्ट (सड़ा हुआ बदबूदार तना) तथा पत्तियों पर गोल छेदों की कतार।",
        solutionEn: "Apply soil granules at planting or first irrigation and spray at shoot emergence.",
        solutionHi: "बुवाई के समय या पहली सिंचाई पर दानेदार कीटनाशक का उपयोग करें।",
        recommendedProduct: "Syngenta Virtako® (Granule) or Ampligo® (Foliar)",
        category: "Insecticide",
        activeIngredient: "Chlorantraniliprole 0.5% + Thiamethoxam 1% GR",
        dosePerAcre: "4 kg/acre (Soil application with light irrigation)",
        waterLitersPerAcre: 200,
        timing: "At 30–45 days after planting in moist soil",
      },
      {
        name: "Red Rot & Pokkah Boeng (Lal Sadand & Pokkah Boeng)",
        nameHi: "लाल सड़न (Red Rot) एवं पोक्का बोइंग",
        type: "fungal_disease",
        symptomsEn: "Yellowing and wilting of third/fourth leaf; internal pith turns red with white transverse bands and alcohol odour.",
        symptomsHi: "गन्ने के अंदर का गूदा लाल पड़ना, सफेद धारियां व शराब जैसी गंध आना; पत्तियां मुड़कर सड़ना।",
        solutionEn: "Use certified disease-free setts, sett treatment, and foliar spray at early twisted leaf stage.",
        solutionHi: "बीज शोधन करें और पोक्का बोइंग के शुरुआती मुड़े पत्तों पर फफूंदनाशक का छिड़काव करें।",
        recommendedProduct: "Syngenta Amistar Top® or Ridomil Gold®",
        category: "Fungicide",
        activeIngredient: "Azoxystrobin + Difenoconazole / Metalaxyl-M + Mancozeb",
        dosePerAcre: "250 ml/acre (Amistar Top)",
        waterLitersPerAcre: 250,
        timing: "During pre-monsoon and onset of humidity",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 4. PULSES
  // ─────────────────────────────────────────────────────────────
  chana: {
    cropId: "chana",
    nameEn: "Gram / Chickpea / Chana (चना)",
    nameHi: "चना",
    category: "pulse",
    season: "Rabi",
    standardVariety: "JG-11 / Dollar Chana / JAKI-9218 / Vishal",
    optimalDayTemp: 24,
    heatStressLimitDay: 34,
    optimalNightTemp: 12,
    nightHeatStressLimit: 22,
    frostTemp: 0,
    baseGdd: 6,
    waterReqMm: [250, 400],
    criticalStages: ["Branching (30-35 DAS)", "Pre-Flowering (45-50 DAS)", "Pod Development (65-75 DAS)"],
    fertilizerNpkKgPerAcre: [10, 24, 10],
    stressBusterRecommendation: {
      product: "Syngenta Quantis®",
      dosePerAcre: "250 ml/acre",
      waterLiters: 150,
      timing: "At flower bud initiation or sudden frost/heat warning",
      benefit: "Reduces flower drop and protects ovule viability under dry spells or high day temperatures.",
    },
    diseasesAndPests: [
      {
        name: "Gram Pod Borer (Helicoverpa armigera / Gheti Ki Illy)",
        nameHi: "चना का फली छेदक (घेंटी की इल्ली)",
        type: "insect_pest",
        symptomsEn: "Caterpillars boring half of their body inside pods, leaving hollowed damaged seeds.",
        symptomsHi: "इल्ली का आधा शरीर फली के अंदर और आधा बाहर रहकर दाना खाना, फलियों में गोल छेद।",
        solutionEn: "Spray at 1 larva/meter row or 5-10% damaged pods window.",
        solutionHi: "फलियों में दाना बनते समय इल्ली दिखते ही तुरंत छिड़काव करें।",
        recommendedProduct: "Syngenta Ampligo®",
        category: "Insecticide",
        activeIngredient: "Chlorantraniliprole 10% + Lambda-cyhalothrin 5% ZC",
        dosePerAcre: "80–100 ml/acre",
        waterLitersPerAcre: 150,
        timing: "Late afternoon or early morning at pod formation",
      },
      {
        name: "Fusarium Wilt & Collar Rot (Ukhta / Sookha Rog)",
        nameHi: "उकठा रोग (Fusarium Wilt) एवं जड़ सड़न",
        type: "fungal_disease",
        symptomsEn: "Drooping of petioles, sudden drying of entire plant in patches; internal root xylem shows dark brown discoloration.",
        symptomsHi: "पौधों का अचानक मुरझाना और सूखना, जड़ को चीरने पर अंदर भूरी-काली नसें दिखना।",
        solutionEn: "Seed treatment before sowing and drenching with systemic fungicide.",
        solutionHi: "बुवाई से पहले बीज उपचार करें व रोगग्रस्त क्यारियों में फफूंदनाशक का ड्रेन्चिंग करें।",
        recommendedProduct: "Syngenta Ridomil Gold®",
        category: "Fungicide",
        activeIngredient: "Metalaxyl-M 4% + Mancozeb 64% WP",
        dosePerAcre: "300–400 g/acre (Drenching / Spray)",
        waterLitersPerAcre: 150,
        timing: "At first sign of wilting patches",
      },
    ],
  },

  tur: {
    cropId: "tur",
    nameEn: "Pigeonpea / Arhar / Tur (तुअर / अरहर)",
    nameHi: "तुअर / अरहर",
    category: "pulse",
    season: "Kharif",
    standardVariety: "BDN-711 / Asha / Maruti / BSMR-736",
    optimalDayTemp: 30,
    heatStressLimitDay: 38,
    optimalNightTemp: 20,
    nightHeatStressLimit: 28,
    frostTemp: 4,
    baseGdd: 10,
    waterReqMm: [600, 900],
    criticalStages: ["Branching (40-50 DAS)", "Flowering (100-115 DAS)", "Pod Filling (125-145 DAS)"],
    fertilizerNpkKgPerAcre: [12, 28, 12],
    stressBusterRecommendation: {
      product: "Syngenta Quantis® + Isabion®",
      dosePerAcre: "350 ml/acre",
      waterLiters: 175,
      timing: "Peak flowering stage",
      benefit: "Reduces heavy flower drop and stimulates vigorous pod setting.",
    },
    diseasesAndPests: [
      {
        name: "Pod Borer & Pod Fly (Maruca & Helicoverpa / Phali Chhedak)",
        nameHi: "फली छेदक इल्ली एवं फल मक्खी (Pod Fly)",
        type: "insect_pest",
        symptomsEn: "Webbed flowers and pods, exit holes on pods with inner grain eaten or deformed.",
        symptomsHi: "फूलों और फलियों का जाले से बंधना, फलियों में छेद और अंदर का दाना खराब होना।",
        solutionEn: "Spray during flower bud stage and repeat 15 days later at pod formation.",
        solutionHi: "फूल खिलने से ठीक पहले और फिर फली बनते समय छिड़काव करें।",
        recommendedProduct: "Syngenta Ampligo®",
        category: "Insecticide",
        activeIngredient: "Chlorantraniliprole 10% + Lambda-cyhalothrin 5% ZC",
        dosePerAcre: "100 ml/acre",
        waterLitersPerAcre: 175,
        timing: "Early morning at 50% flowering",
      },
      {
        name: "Phytophthora Stem Blight & Sterility Mosaic",
        nameHi: "तना झुलसा एवं बांझपन मोजेक (Sterility Mosaic)",
        type: "fungal_disease",
        symptomsEn: "Dark brown necrotic lesions on main stem; bushy sterile plants without flower/pod formation.",
        symptomsHi: "तने पर गहरे भूरे धब्बे, पौधे का झाड़ीदार हो जाना और उस पर फूल-फली न लगना।",
        solutionEn: "Spray Ridomil Gold at stem lesions; spray acaricide for mite vector of sterility mosaic.",
        solutionHi: "तना झुलसा दिखने पर फफूंदनाशक का छिड़काव करें।",
        recommendedProduct: "Syngenta Ridomil Gold®",
        category: "Fungicide",
        activeIngredient: "Metalaxyl-M + Mancozeb",
        dosePerAcre: "300 g/acre",
        waterLitersPerAcre: 175,
        timing: "During cloudy, high-humidity monsoon periods",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 5. VEGETABLES & HORTICULTURE
  // ─────────────────────────────────────────────────────────────
  tomato: {
    cropId: "tomato",
    nameEn: "Tomato (टमाटर)",
    nameHi: "टमाटर",
    category: "vegetable",
    season: "Year-Round",
    standardVariety: "Syngenta Abhinav / TO-1057 / US-440 / Arka Rakshak",
    optimalDayTemp: 26,
    heatStressLimitDay: 35,
    optimalNightTemp: 16,
    nightHeatStressLimit: 24,
    frostTemp: 2,
    baseGdd: 10,
    waterReqMm: [600, 800],
    criticalStages: ["Transplanting", "Flowering & Fruit Set", "Fruit Development & Harvesting"],
    fertilizerNpkKgPerAcre: [40, 30, 30],
    stressBusterRecommendation: {
      product: "Syngenta Quantis® + Isabion®",
      dosePerAcre: "300 ml/acre",
      waterLiters: 150,
      timing: "During high flowering and temperature fluctuations",
      benefit: "Prevents blossom end rot and heavy flower drop during extreme heat.",
    },
    diseasesAndPests: [
      {
        name: "Early & Late Blight (Agheti v Pichheti Jhulsa)",
        nameHi: "टमाटर का अगेती एवं पछेती झुलसा (Blight)",
        type: "fungal_disease",
        symptomsEn: "Concentric target rings on leaves (Early) or water-soaked black-brown rotting patches on leaves and fruits (Late).",
        symptomsHi: "पत्तियों पर छल्लेदार धब्बे अथवा पानी से भीगे हुए काले-भूरे सड़न वाले चकत्ते, फल खराब होना।",
        solutionEn: "Spray Ridomil Gold or Amistar Top proactively before rain spells.",
        solutionHi: "बारिश व अधिक नमी के समय सुरक्षात्मक रूप से फफूंदनाशक का छिड़काव करें।",
        recommendedProduct: "Syngenta Ridomil Gold® or Amistar Top®",
        category: "Fungicide",
        activeIngredient: "Metalaxyl-M + Mancozeb / Azoxystrobin + Difenoconazole",
        dosePerAcre: "300 g/acre (Ridomil) or 200 ml/acre (Amistar Top)",
        waterLitersPerAcre: 150,
        timing: "Early morning upon leaf wetness detection",
      },
      {
        name: "Tomato Leaf Curl Virus - ToLCV & Whitefly / Tuta Absoluta",
        nameHi: "पत्ता मरोड़ वायरस (Leaf Curl) एवं पिनवर्म (Tuta)",
        type: "insect_pest",
        symptomsEn: "Leaves curling upwards, thickening, stunted bushy plant; pinworm mining inside fruit and leaves.",
        symptomsHi: "पत्तियां ऊपर की ओर मुड़ना, पौधा बौना रह जाना तथा फलों में इल्ली द्वारा छेद।",
        solutionEn: "Control whitefly vector with Pegasus/Alika and spray Ampligo for Tuta leaf miner.",
        solutionHi: "सफेद मक्खी को रोकने के लिए पेगासस तथा फल छेदक/टूटा के लिए एम्पलीगो का छिड़काव करें।",
        recommendedProduct: "Syngenta Pegasus® (Vector) + Ampligo® (Fruit Borer)",
        category: "Insecticide Combo",
        activeIngredient: "Diafenthiuron 50% WP / Chlorantraniliprole + Lambda-cyhalothrin",
        dosePerAcre: "200 g/acre (Pegasus) or 80 ml/acre (Ampligo)",
        waterLitersPerAcre: 150,
        timing: "Early morning spraying underneath leaves",
      },
    ],
  },

  onion: {
    cropId: "onion",
    nameEn: "Onion / Garlic (प्याज / लहसुन)",
    nameHi: "प्याज / लहसुन",
    category: "vegetable",
    season: "Rabi",
    standardVariety: "Nasik Red / Bhima Super / Agrifound Light Red / G-282 Garlic",
    optimalDayTemp: 24,
    heatStressLimitDay: 34,
    optimalNightTemp: 14,
    nightHeatStressLimit: 22,
    frostTemp: 0,
    baseGdd: 6,
    waterReqMm: [400, 600],
    criticalStages: ["Transplanting (0-30 DAT)", "Vegetative (30-60 DAT)", "Bulb Development (60-90 DAT)", "Bulb Maturation"],
    fertilizerNpkKgPerAcre: [30, 20, 20],
    stressBusterRecommendation: {
      product: "Syngenta Quantis® + Isabion®",
      dosePerAcre: "300 ml/acre",
      waterLiters: 150,
      timing: "Bulb enlargement stage (60–75 DAT)",
      benefit: "Enhances uniform bulb sizing, skin luster, and storage shelf-life.",
    },
    diseasesAndPests: [
      {
        name: "Onion Thrips (Thrips tabaci / Peele Keede)",
        nameHi: "प्याज का थ्रिप्स (सफेद धब्बे / रस चूसक कीट)",
        type: "insect_pest",
        symptomsEn: "Silvery-white patches and streaks on leaves, tips drying and curling, reduced bulb size.",
        symptomsHi: "पत्तियों पर चांदी जैसे सफेद धब्बे व धारियां, पत्तियों के ऊपरी सिरे सूखना।",
        solutionEn: "Spray systemically with surfactant for waxy onion foliage.",
        solutionHi: "प्याज के चिकने पत्तों पर दवा चिपकने हेतु सिलिकॉन स्टीकर मिलाकर छिड़काव करें।",
        recommendedProduct: "Syngenta Pegasus® or Alika®",
        category: "Insecticide",
        activeIngredient: "Diafenthiuron 50% WP / Thiamethoxam + Lambda-cyhalothrin",
        dosePerAcre: "200 g/acre (Pegasus) or 80 ml/acre (Alika)",
        waterLitersPerAcre: 150,
        timing: "Early morning directed into leaf sheaths",
      },
      {
        name: "Purple Blotch & Stemphylium Blight (Kalyani / Baingani Dhabba)",
        nameHi: "बैंगनी धब्बा रोग (Purple Blotch) एवं झुलसा",
        type: "fungal_disease",
        symptomsEn: "Small water-soaked sunken lesions turning brown to dark purple with yellow halo, drying foliage.",
        symptomsHi: "पत्तियों पर बैंगनी रंग के धब्बे जो बीच में गहरे और किनारों पर पीले होते हैं, पत्तियां सूखना।",
        solutionEn: "Apply Amistar Top or Ridomil Gold at first purple spot appearance.",
        solutionHi: "बैंगनी धब्बा दिखते ही फफूंदनाशक का तुरंत छिड़काव करें।",
        recommendedProduct: "Syngenta Amistar Top®",
        category: "Fungicide",
        activeIngredient: "Azoxystrobin 18.2% + Difenoconazole 11.4% SC",
        dosePerAcre: "200 ml/acre",
        waterLitersPerAcre: 150,
        timing: "Morning spray with sticker at bulb initiation",
      },
    ],
  },

  potato: {
    cropId: "potato",
    nameEn: "Potato (आलू)",
    nameHi: "आलू",
    category: "vegetable",
    season: "Rabi",
    standardVariety: "Kufri Chipsona / Pukhraj / Jyoti / Badshah",
    optimalDayTemp: 20,
    heatStressLimitDay: 30,
    optimalNightTemp: 12,
    nightHeatStressLimit: 20,
    frostTemp: -1,
    baseGdd: 4,
    waterReqMm: [400, 600],
    criticalStages: ["Stolon Initiation (20-30 DAS)", "Tuber Bulking (40-60 DAS)", "Tuber Maturation (70-90 DAS)"],
    fertilizerNpkKgPerAcre: [48, 32, 40],
    stressBusterRecommendation: {
      product: "Syngenta Quantis®",
      dosePerAcre: "300 ml/acre",
      waterLiters: 150,
      timing: "Tuber bulking stage under frost risk or daytime heat",
      benefit: "Maintains uninterrupted starch accumulation and protects against frost shock.",
    },
    diseasesAndPests: [
      {
        name: "Late Blight of Potato (Phytophthora infestans / Pichheti Jhulsa)",
        nameHi: "आलू का पछेती झुलसा (Late Blight)",
        type: "fungal_disease",
        symptomsEn: "Water-soaked irregular black lesions on leaves with white mould underneath in foggy cool weather, rotten tubers.",
        symptomsHi: "कोहरे और ठंड में पत्तियों पर गीले काले धब्बे, निचली सतह पर सफेद फफूंद तथा आलू का सड़ना।",
        solutionEn: "Apply Ridomil Gold proactively when relative humidity exceeds 85% and night temp is 10-18°C.",
        solutionHi: "कोहरा व 85% से अधिक नमी होते ही तुरंत रिडोमिल गोल्ड का छिड़काव करें।",
        recommendedProduct: "Syngenta Ridomil Gold® or Revus®",
        category: "Fungicide",
        activeIngredient: "Metalaxyl-M 4% + Mancozeb 64% WP / Mandipropamid",
        dosePerAcre: "300–400 g/acre (Ridomil)",
        waterLitersPerAcre: 150,
        timing: "Proactive foliar spray before cloud cover/fog",
      },
      {
        name: "Aphids & Potato Tuber Moth (Mahun & PTM)",
        nameHi: "आलू का माहू एवं कंद कीट (Tuber Moth)",
        type: "insect_pest",
        symptomsEn: "Aphids transmitting leaf roll virus; caterpillars tunneling inside stored or exposed tubers.",
        symptomsHi: "माहू द्वारा वायरस फैलाना तथा खेत व भंडार में आलू के अंदर इल्ली द्वारा सुरंग बनाना।",
        solutionEn: "Apply Actara for aphids and proper earthing up to prevent tuber exposure.",
        solutionHi: "माहू के लिए एक्टारा का छिड़काव करें तथा आलुओं पर मिट्टी अच्छी तरह चढ़ाएं।",
        recommendedProduct: "Syngenta Actara® (Foliar)",
        category: "Insecticide",
        activeIngredient: "Thiamethoxam 25% WG",
        dosePerAcre: "60–80 g/acre",
        waterLitersPerAcre: 150,
        timing: "Early vegetative and tuber formation stages",
      },
    ],
  },

  chilli: {
    cropId: "chilli",
    nameEn: "Chilli / Pepper (मिर्च)",
    nameHi: "मिर्च",
    category: "vegetable",
    season: "Year-Round",
    standardVariety: "G4 / Teja / Syngenta HPH-5531 / Armoor",
    optimalDayTemp: 28,
    heatStressLimitDay: 38,
    optimalNightTemp: 18,
    nightHeatStressLimit: 26,
    frostTemp: 2,
    baseGdd: 10,
    waterReqMm: [600, 900],
    criticalStages: ["Transplanting", "Vegetative & Branching", "Flowering & Fruit Setting", "Harvest Flushes"],
    fertilizerNpkKgPerAcre: [40, 24, 24],
    stressBusterRecommendation: {
      product: "Syngenta Isabion® + Quantis®",
      dosePerAcre: "350 ml/acre",
      waterLiters: 150,
      timing: "At start of every flowering flush",
      benefit: "Maximizes flower retention, fruit elongation, and pungency index.",
    },
    diseasesAndPests: [
      {
        name: "Chilli Murda Complex (Thrips & Mites / Murda Rog)",
        nameHi: "मिर्च का मरोड़िया रोग (थ्रिप्स एवं माइट्स)",
        type: "insect_pest",
        symptomsEn: "Boat-shaped upward leaf curling (Thrips) and downward inverted cup curling (Yellow Mites), brittle foliage.",
        symptomsHi: "पत्तियों का ऊपर नाव की तरह मुड़ना (थ्रिप्स) अथवा नीचे की ओर मुड़ना (माइट्स), पत्तियों का कड़ा होना।",
        solutionEn: "Spray Pegasus or Minecto Pro targeting both thrips and mites simultaneously.",
        solutionHi: "थ्रिप्स और माइट्स दोनों के एक साथ नियंत्रण हेतु पेगासस का छिड़काव करें।",
        recommendedProduct: "Syngenta Pegasus® or Minecto Pro®",
        category: "Insecticide / Acaricide",
        activeIngredient: "Diafenthiuron 50% WP / Cyantraniliprole + Abamectin",
        dosePerAcre: "200–250 g/acre (Pegasus)",
        waterLitersPerAcre: 150,
        timing: "Early morning with complete under-leaf canopy wetting",
      },
      {
        name: "Anthracnose / Fruit Rot & Dieback (Phal Sadand)",
        nameHi: "फल सड़न एवं डाइबैक (Anthracnose)",
        type: "fungal_disease",
        symptomsEn: "Circular sunken black spots with concentric rings on ripe chillies, twigs drying from tip downwards (Dieback).",
        symptomsHi: "पकी लाल मिर्च पर गोल काले धब्बे, टहनियों का ऊपर से नीचे की ओर सूखना (डाइबैक)।",
        solutionEn: "Spray Amistar Top at first fruit setting and repeat after 12 days.",
        solutionHi: "फल बनते ही फफूंदनाशक का छिड़काव करें।",
        recommendedProduct: "Syngenta Amistar Top®",
        category: "Fungicide",
        activeIngredient: "Azoxystrobin 18.2% + Difenoconazole 11.4% SC",
        dosePerAcre: "200 ml/acre",
        waterLitersPerAcre: 150,
        timing: "At flowering to green fruit development stage",
      },
    ],
  },
};

/**
 * Helper to fetch agronomic knowledge profile for any crop ID or natural name
 */
export function getCropAdvisoryProfile(cropName: string): CropAgronomicProfile {
  const norm = (cropName || "").toLowerCase().trim();

  // 1. Direct match
  if (CROP_ADVISORY_MATRIX[norm]) {
    return CROP_ADVISORY_MATRIX[norm];
  }

  // 2. Partial match
  for (const [key, profile] of Object.entries(CROP_ADVISORY_MATRIX)) {
    if (
      norm.includes(key) ||
      norm.includes(profile.nameEn.toLowerCase()) ||
      norm.includes(profile.nameHi.toLowerCase()) ||
      profile.nameEn.toLowerCase().includes(norm)
    ) {
      return profile;
    }
  }

  // 3. Dynamic generic agronomic fallback profile for any unlisted crop
  return {
    cropId: norm.slice(0, 20) || "general_crop",
    nameEn: cropName || "Field Crop",
    nameHi: cropName || "फसल",
    category: "cash_crop",
    season: "Year-Round",
    standardVariety: "Standard Commercial Variety",
    optimalDayTemp: 28,
    heatStressLimitDay: 38,
    optimalNightTemp: 20,
    nightHeatStressLimit: 28,
    frostTemp: 2,
    baseGdd: 10,
    waterReqMm: [500, 800],
    criticalStages: ["Vegetative Growth", "Flowering Stage", "Fruit / Seed Filling"],
    fertilizerNpkKgPerAcre: [30, 20, 20],
    stressBusterRecommendation: {
      product: "Syngenta Quantis® / Isabion®",
      dosePerAcre: "300 ml/acre",
      waterLiters: 150,
      timing: "Flowering or temperature stress onset",
      benefit: "Relieves abiotic heat/drought stress and stimulates active plant recovery.",
    },
    diseasesAndPests: [
      {
        name: "Sucking & Foliar Pests (Keeda / Ras Choosak)",
        nameHi: "रस चूसक एवं पत्ती खाने वाले कीट",
        type: "insect_pest",
        symptomsEn: "Leaf curling, holes on foliage, honeydew secretion, or flower drop.",
        symptomsHi: "पत्तियों का मुड़ना, पत्तों में छेद अथवा फूलों का गिरना।",
        solutionEn: "Apply targeted insecticide with appropriate water volume.",
        solutionHi: "शुरुआती लक्षण दिखते ही उचित कीटनाशक का छिड़काव करें।",
        recommendedProduct: "Syngenta Ampligo® or Alika®",
        category: "Insecticide",
        activeIngredient: "Chlorantraniliprole / Thiamethoxam",
        dosePerAcre: "100 ml/acre",
        waterLitersPerAcre: 150,
        timing: "Early morning or late afternoon",
      },
      {
        name: "Fungal Leaf Spots & Blight (Fafund Rog / Jhulsa)",
        nameHi: "पत्ती धब्बा एवं फफूंद झुलसा रोग",
        type: "fungal_disease",
        symptomsEn: "Brown or black lesions on foliage, yellow halos, premature leaf drop.",
        symptomsHi: "पत्तियों पर भूरे-काले धब्बे और पत्तों का सूखकर गिरना।",
        solutionEn: "Spray broad-spectrum systemic fungicide.",
        solutionHi: "सुरक्षात्मक रूप से फफूंदनाशक का छिड़काव करें।",
        recommendedProduct: "Syngenta Amistar Top®",
        category: "Fungicide",
        activeIngredient: "Azoxystrobin + Difenoconazole",
        dosePerAcre: "200 ml/acre",
        waterLitersPerAcre: 150,
        timing: "At first spot appearance",
      },
    ],
  };
}
